# Install this file to:
#   /etc/rsyslog.d/30-fortigate.conf

module(load="imudp")

template(name="FortiGateRawNoPri" type="list") {
  property(name="rawmsg-after-pri")
  constant(value="\n")
}

input(type="imudp" port="514" ruleset="fortigate")

ruleset(name="fortigate") {
  action(
    type="omfile"
    file="/var/log/fortigate/incoming.log"
    template="FortiGateRawNoPri"
    createDirs="on"
    DirCreateMode="0750"
    FileCreateMode="0640"
  )
}
