/var/log/fortigate/*.log {
    daily
    rotate 14
    missingok
    notifempty
    compress
    dateext
    dateformat -%Y%m%d
    create 0640 syslog adm
    sharedscripts
    postrotate
        systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true
    endscript
}
